In [1]:
import numpy as nm 
import time

l1=[1,2,3,4,5,6,7,8,9,6,2,3,4,5,6,6,7,8]

start = time.time()
sqr=[x**2 for x in l1]
end=time.time()
print(end-start)

l2=nm.array([1,2,3,4,5,6,7,8,9,6,2,3,4,5,6,6,7,8])


start = time.time()
sqq=l2**2
end=time.time()

print(end-start)



9.989738464355469e-05
9.226799011230469e-05


In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
arr=nm.array([100,99,98,97,87])
print(arr)

a=arr.dtype
b=arr.ndim
c=arr.shape

print(a)
print(b)
print(c)

[100  99  98  97  87]
int64
1
(5,)


In [4]:
sum = arr.sum()
print(sum)

avg= arr.mean()
print(avg)

print(arr.max())
print(arr.min())

481
96.2
100
87


In [5]:
# adding 5 to all    

newarr=arr+5

print(newarr)

[105 104 103 102  92]


In [6]:
passed=arr[arr>=98]              # apply condision / filtering

print(passed)

[100  99  98]


In [7]:
passed.size

3

In [8]:
newarr=nm.array([100,99,98,97,96,95])
newarr.reshape((2,3))

array([[100,  99,  98],
       [ 97,  96,  95]])

In [9]:
new=nm.random.randint(1,101,20)                  # 1-100 random
print(new)
new.reshape((5,4))

[36 54  3 62 59 73 22 99 96 66 92 22 54 80 54 73 85 73 60 23]


array([[36, 54,  3, 62],
       [59, 73, 22, 99],
       [96, 66, 92, 22],
       [54, 80, 54, 73],
       [85, 73, 60, 23]], dtype=int32)

In [10]:
neww=nm.random.randint(1,10,(3,3))

In [11]:
print(neww)

[[6 6 1]
 [2 8 4]
 [4 8 7]]


In [12]:
arr = nm.array([1, 2, 3, 4, 5])


In [13]:
arr


array([1, 2, 3, 4, 5])

In [14]:
arr.dtype


dtype('int64')

In [15]:
z = nm.zeros(20)


In [16]:
z.dtype

dtype('float64')

In [17]:
z = nm.zeros(20, dtype="int64")


In [18]:
z.dtype

dtype('int64')

In [19]:
nmm = z + 3


In [20]:
nmm

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [21]:

nm.dtype

numpy.dtype

In [22]:
nm.array([1,2])

array([1, 2])

In [23]:
z.shape

(20,)

In [24]:
nm.full(20,7)

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [25]:
nm.arange(1,11,5)                   # i to  n-1   x dif

array([1, 6])

In [26]:
nm.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [27]:
nm.eye(3)    # default float

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
nm.eye(3,dtype="int64")

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [29]:
nm.random.randint(1,10,20)      # i to n-1 , x num

array([3, 9, 7, 2, 5, 4, 4, 9, 4, 6, 2, 4, 3, 2, 7, 1, 9, 7, 9, 8],
      dtype=int32)

In [30]:
arr=nm.array([[[1,2,3],[4,5,6],[7,8,9]],[[11,2,3],[4,88,6],[7,8,99]]])

In [31]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11,  2,  3],
        [ 4, 88,  6],
        [ 7,  8, 99]]])

In [32]:
arr.shape

(2, 3, 3)

In [33]:
arr.ndim

3

In [34]:
arr.size

18

In [35]:
arr.dtype

dtype('int64')

In [36]:
arr.astype(float)

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.]],

       [[11.,  2.,  3.],
        [ 4., 88.,  6.],
        [ 7.,  8., 99.]]])

In [37]:
arr.dtype

dtype('int64')

In [38]:
arrf=arr.astype(float)

In [39]:
arrf

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.]],

       [[11.,  2.,  3.],
        [ 4., 88.,  6.],
        [ 7.,  8., 99.]]])

In [40]:
arrf.dtype

dtype('float64')

In [41]:
arr[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
arr[0,1]

array([4, 5, 6])

In [43]:
arr[1,0]

array([11,  2,  3])

In [44]:
arr[0,]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
ar=arr.reshape(3,6)

In [46]:
ar

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 11,  2,  3],
       [ 4, 88,  6,  7,  8, 99]])

In [47]:
arr.flatten()    # convert into 1 dnmsn 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11,  2,  3,  4, 88,  6,  7,  8,
       99])

In [48]:
arr.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11,  2,  3,  4, 88,  6,  7,  8,
       99])

In [49]:
a=nm.array([1,2,3,4])
b=nm.array([11,22,33,44])

c=a+b

In [50]:
c

array([12, 24, 36, 48])

In [51]:
c=nm.concatenate((a,b))

In [52]:
c

array([ 1,  2,  3,  4, 11, 22, 33, 44])

In [53]:
nm.vstack((a,b))

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [54]:
nm.hstack((a,b))

array([ 1,  2,  3,  4, 11, 22, 33, 44])

In [55]:
nm.split(arr,2)       # equal division

[array([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]),
 array([[[11,  2,  3],
         [ 4, 88,  6],
         [ 7,  8, 99]]])]

In [57]:
nm.add(a,b)    #// element position wise jog

array([12, 24, 36, 48])

In [58]:
r=nm.sqrt(a)
r

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [59]:
r.dtype

dtype('float64')

In [60]:
nm.power(a,3)

array([ 1,  8, 27, 64])

In [61]:
abb=nm.median(a)
abb

np.float64(2.5)

In [62]:
r

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [63]:
a

array([1, 2, 3, 4])

In [64]:
a=nm.array([34,795,75,367,245,75,6,23,678,42,678,3,555,798,2,644,7,2,1,1,0])

In [67]:
nm.sort(a)

array([  0,   1,   1,   2,   2,   3,   6,   7,  23,  34,  42,  75,  75,
       245, 367, 555, 644, 678, 678, 795, 798])

In [69]:
a

array([  0,   1,   1,   2,   2,   3,   6,   7,  23,  34,  42,  75,  75,
       245, 367, 555, 644, 678, 678, 795, 798])

In [70]:
a=nm.array([34,795,75,367,245,75,6,23,678,42,678,3,555,798,2,644,7,2,1,1,0])

In [72]:
nm.argsort(a)    # firsly sort secondly give there past position

array([20, 18, 19, 17, 14, 11,  6, 16,  7,  0,  9,  5,  2,  4,  3, 12, 15,
        8, 10,  1, 13])

In [74]:
nm.where(a>33)

(array([ 0,  1,  2,  3,  4,  5,  8,  9, 10, 12, 13, 15]),)

In [75]:
a[a>5]

array([ 34, 795,  75, 367, 245,  75,   6,  23, 678,  42, 678, 555, 798,
       644,   7])

In [76]:
a

array([ 34, 795,  75, 367, 245,  75,   6,  23, 678,  42, 678,   3, 555,
       798,   2, 644,   7,   2,   1,   1,   0])

That's it